### ISSUE TITLE
Checkpoint Merger Error

### ISSUE THREAD

**Issue by AvaCadava** [lllyasviel/stable-diffusion-webui-forge#1095]
*** Error loading/saving model file██████████████████████████████████████████████████| 140/140 [00:40<00:00,  3.71it/s]
    Traceback (most recent call last):
      File "F:\AI\StableDiffusion\WebUI-Forge\modules\ui_checkpoint_merger.py", line 21, in modelmerger
        results = extras.run_modelmerger(*args)
      File "F:\AI\StableDiffusion\WebUI-Forge\modules\extras.py", line 135, in run_modelmerger
        primary_model_info = sd_models.checkpoints_list[primary_model_name]
    KeyError: 'SD15_AvaCadava_v6_EP150.safetensors'

---

I tried different models / combinations and all of them failed with the same error. I get this error since I've updated to the new UI design with FLUX integration. Before the Update I had no problems to merge my models.

**Comment by ayyRyuu** [comment]
I am getting the same error. I tried multiple fixes but none of them worked.

**Comment by nbzncloud** [comment]
Same issue. I've always used Forge and I do a lot of checkpoint merges, but after the flux update I can't merge anything anymore. I'm having to use A1111 for this now.

**Comment by raiken92** [comment]
I have the exact same issue too. Everything was working fine and then after I updated it stopped working. Are there any fixes yet?

**Comment by cluder** [comment]
see also #1359, i found some problems, the KeyError seems to come from forge searching with 'SD15_AvaCadava_v6_EP150.safetensors'  but the list of checkpoints has the key like: 'SD15_AvaCadava_v6_EP150.safetensors [somehash]'  so it can't match

**Comment by cluder** [comment]
should be fixed now

**Comment by ayyRyuu** [comment]
> should be fixed now

Normally merging two checkpoints works fine but I'm getting "'NoneType' object has no attribute 'keys'" error when I try to add difference on three models

**Comment by ssbugman** [comment]
> ge and I do a lot of checkpoint merges, but after the flux upd

Not fixed, now it become even worse and UI hangs on "waiting" after error.
Still "Error merging checkpoints: 'NoneType' object has no attribute 'keys'"
